### ISSUE TITLE
Mod shows in Minecraft but nothing is added

### ISSUE THREAD

**Issue by CosmerTroll** [gbl/EasierVillagerTrading#22]
I used multiple versions of the mod but none of the blocks / features were added into Minecraft. Shows the option to make the shift buy all thing but nothing is actually inside the game.

**Comment by gbl** [comment]
As mentioned in the description, the mod doesn't bring it's own GUI anymore since version 1.14.

Until 1.13, there was no way to quickly select a specific trade in Minecraft itself, so the mod showed a list of possible trades. That's what the old screenshots still have. But from 1.14 on, MC has the trades list itself, so the mod doesn't show a list anymore, it just redefines the behaviour of the buttons. Pressing a button executes a trade once instead of just moving the trade to the villager window.

**Comment by CosmerTroll** [comment]
Yeah but i also cant pick up villagers or craft any of the blocks added from the mod like the glass box trading thing. Its not the gui that works i just cant pick up villagers as a whole.

**Comment by gbl** [comment]
You seem to be confusing the mod with another one. My mod allows you to single-click-trade with villagers. It has no "glass box trading thing" and doesn't allow you to pick up villagers.

**Comment by CosmerTroll** [comment]
oh thats my mistake, sorry for inconveniencing you. i mostly do all my mod stuff at 3 am since I forget about it at the morning/
